# Cholesky Factorization

In this notebook, we will implement Cholesky directly from Algorithm 6.6 in Burden, Faires, and Burden, 10th edition.  We will then compare it to Python's built-in Cholesky method.

# DIY: Cholesky Factorization

The Cholesky Factorization is only for symmetric, positive definite matrices.  Therefore, we need to develop a check for a matrix that is inputted into our method.

## Symmetry Check

First we check if it is symmetric.  This inherently will also tell us if the matrix is square.

In [ ]:
import numpy as np

# simulate a symmetric matrix
A = np.random.normal(0, 1, (4,4)); S = np.matmul(A.T, A); F = np.random.uniform(0, 1, (3,4));
D = np.array(((1,0,0), (1, 1, 0), (1, 1, 1)))

def symmetry_check(array):

    if not np.array_equal(array, array.T):

        return False

    else:

        return True

Does it output correctly?  If not, correct the issue!

In [ ]:
print(symmetry_check(A))

print(symmetry_check(S))

print(symmetry_check(F))
print(symmetry_check(D))

False
True
False
False


## Positive Definite Check

Thought process:

* Theorem 6.23 can only tell us when a matrix is NOT positive definite.

* Theorem 6.26 in text tells us that if vanilla Gaussian Elimination is performed (without row interchanges) and results in an echelon form with positive pivot elements, then the original matrix is positive definite. ... It seems costly to me to do G.E. first just to check if something is positive definite.  

* So, what we will do is go ahead and perform Cholesky.  If anything goes awry, then we'll know the input matrix was NOT positive definite.

Double check thinking with respect to theorems 6.23 and 6.26.  If you feel like they can be used, say so in this text box.  If you agree with the thinking stated above, expand on that thinking in this text box.

## Alg 6.6: DIY Cholesky Factorization

Below is an interpretation of the pseudocode provided by our textbook.  It is skeletal code, so please check spots where you need to fill in blanks!

In [ ]:
# Input: a square numpy array A
# Output: a square numpy array L - lower triangular matrix
def diy_cholesky(A):
  # step 1: symmetry check
  symmetric = symmetry_check(A)
  if not symmetric:
      return "Matrix is not Symmetric"

  # step 2: if symmetry check passes, then record size of A
  (n,m) = A.shape

  # step 2: initialize L
  L = np.zeros((n,m))

  # step 3: set l_11 = sqrt(a_11)
  L[0,0] = np.sqrt(A[0,0])

  # step 4: a for loop that fills in the first column of L
  for j in range(1, n):

      L[j,0] = A[j,0]/L[0,0]

  # step 5: another loop for remaining columns
  for i in range(1, m-1):

      sum_term = np.sum(L[i, :i]**2) # don't forget that it does NOT include i, in :
      L[i,i] = np.sqrt(A[i,i] - sum_term) #fill in blank

      #step 6: another loop for elements below diagonal term
      for k in range(i+1, n):
          new_sum_term = np.sum(L[k, :(i-1)]*L[i, :(i-1)])
          divisor = L[i,i]
          L[k,i] = (A[k,i] - new_sum_term)/divisor

  # step 7: fill in last term of L
  to_sqrt = (A[n-1,m-1] - np.sum(L[n-1, :(n-1)]**2))
  if (to_sqrt < 0):
      return "Matrix is not Positive Definite"
  else:
      L[n-1,m-1] = np.sqrt(to_sqrt)
  return L

print(diy_cholesky(F))

Matrix is not Symmetric


We can add a check at the end here.  If $LL^T$ is equal to input matrix $A$, then return $L$.  Otherwise, return "Matrix is not Positive Definite".  We expect, at the very least, that if $A$ is not positive definite, then the $LL^T$ decomposition will not equal the original matrix (even if Python thinks an $L$ can be calculated).

### TASK

Your task now is to take the code above from the various sections and create a full function for cholesky factorization.  If there are any other checks you think we need, please be sure to incorporate them and say why they're needed!

In [ ]:
# Input: a square numpy array A
# Output: a square numpy array L - lower triangular matrix
def our_cholesky(A):
  # step 1: symmetry check
  symmetric = symmetry_check(A)
  if not symmetric:
      return "Matrix is not Symmetric"

  # step 2: if symmetry check passes, then record size of A
  (n,m) = A.shape

  # step 2: initialize L
  L = np.zeros((n,m))

  # step 3: set l_11 = sqrt(a_11)
  L[0,0] = np.sqrt(A[0,0])

  # step 4: a for loop that fills in the first column of L
  for j in range(1, n):

      L[j,0] = A[j,0]/L[0,0]

  # step 5: another loop for remaining columns
  for i in range(1, m-1):

      sum_term = np.sum(L[i, :i]**2) # don't forget that it does NOT include i, in :
      L[i,i] = np.sqrt(A[i,i] - sum_term) #fill in blank

      #step 6: another loop for elements below diagonal term
      for k in range(i+1, n):
          new_sum_term = np.sum(L[k, :(i-1)]*L[i, :(i-1)])
          divisor = L[i,i]
          L[k,i] = (A[k,i] - new_sum_term)/divisor

  # step 7: fill in last term of L
  to_sqrt = (A[n-1,m-1] - np.sum(L[n-1, :(n-1)]**2))
  if (to_sqrt < 0):
      return "Matrix is not Positive Definite"
  else:
      L[n-1,m-1] = np.sqrt(to_sqrt)
  return L

Matrix is not Symmetric
[[ 1.14713951  0.          0.          0.        ]
 [-1.95700548  2.19236356  0.          0.        ]
 [ 0.60426393 -0.56870195  1.27952357  0.        ]
 [-1.66078802  0.13142778 -0.49190143  1.57827024]]
Matrix is not Symmetric


### TASK

Test our function on at least three matrices you know are symmetric positive definite and on two matrices you know are *not* symmetric positive definite.  You can use your textbook to find a few.  Demonstrate your tests and results in code chunks below.

Describe the issues you may have run into in the following way:  in a text box below code chunks with resulting issues, put your description.  Also include how you attempted to fix the issues.  Example below.

In [ ]:
print(diy_cholesky(A))
print(diy_cholesky(S))
print(diy_cholesky(F))

Matrix is not Symmetric
[[ 1.14713951  0.          0.          0.        ]
 [-1.95700548  2.19236356  0.          0.        ]
 [ 0.60426393 -0.56870195  1.27952357  0.        ]
 [-1.66078802  0.13142778 -0.49190143  1.57827024]]
Matrix is not Symmetric


Text box describing issue based on output displayed.

In [ ]:
# I have fixed the issues. I think it works. Maybe I will find issues later.

## How Python Does It

Now that you have working code.  We will compare to Python's code.  This is something computational scientists do all the time: invent a method that solves the same problem as an existing method, and then compare in hopes of out-performing the existing method in some respect.

The following code is how you'd implement Cholesky if we were just going to use Python code.

In [ ]:
np.linalg.cholesky(S) # will need to have run code above that imports numpy

array([[ 1.14713951,  0.        ,  0.        ,  0.        ],
       [-1.95700548,  2.19236356,  0.        ,  0.        ],
       [ 0.60426393, -0.02930792,  1.39990839,  0.        ],
       [-1.66078802, -1.35106869, -0.47788589,  0.83451525]])

The one line is very nice.  I'm sure the source code looks similar to our source code.

Since we don't necessarily have access to the source code, we will compare based on time it takes to find $L$.  See the code chunk below for timing Python's method.

In [ ]:
import time

py_start = time.time()
L = np.linalg.cholesky(S)
py_end = time.time() - py_start

In [ ]:
print(f"{py_end:.30f}") # this gives us more decimal places for our float

0.000170469284057617187500000000


### Task

Determine the length of time for *our_cholesky*.  Which method takes less time?  By how much?  What do you think causes the difference?  

In [ ]:
import time

our_start = time.time()
L = our_cholesky(S)
our_end = time.time() - our_start
print(f"{our_end:.30f}")

print(f"Difference between our and python's cholesky times: {(our_end - py_end):.30f}")

0.000271320343017578125000000000
Difference between our and python's cholesky times: 0.000100851058959960937500000000


### Task

Do some research.  Can you find the source code for NumPy's Cholesky?  If so, make notes about the literal differences between our function and theirs.  If you can't find it, what do you find instead?


Create a venn diagram in LaTeX

Python's Cholesky calls a series of other dependencies, including the popular LAPACK library. We've to some level copied in relevant parts of the source code. The top text box has the most top-level calls, and each following box contains the source from the dependency functions it calls. I meant to go even further and try to  make a call graph but this week has been very busy.

I cannot remember if I said 'create a venn diagram in LaTeX or if that was part of the task but I haven't picked apart these functions enough to do that so oh well.

This function linearizes their matrix, which I don't beleive we do to our (unless numpy secretly does that under the hood). It ultimately splits cases for different matrices and calls the appropriate LAPACK functions.


In [ ]:
print(np.__version__)

2.0.2


https://github.com/numpy/numpy/blob/v2.0.2/numpy/linalg/_linalg.py#L738-L840

In [ ]:

# # Cholesky decomposition

# def _cholesky_dispatcher(a, /, *, upper=None):
#     return (a,)


# @array_function_dispatch(_cholesky_dispatcher)
# def cholesky(a, /, *, upper=False):
#     """
#     Cholesky decomposition.

#     Return the lower or upper Cholesky decomposition, ``L * L.H`` or
#     ``U.H * U``, of the square matrix ``a``, where ``L`` is lower-triangular,
#     ``U`` is upper-triangular, and ``.H`` is the conjugate transpose operator
#     (which is the ordinary transpose if ``a`` is real-valued). ``a`` must be
#     Hermitian (symmetric if real-valued) and positive-definite. No checking is
#     performed to verify whether ``a`` is Hermitian or not. In addition, only
#     the lower or upper-triangular and diagonal elements of ``a`` are used.
#     Only ``L`` or ``U`` is actually returned.

#     Parameters
#     ----------
#     a : (..., M, M) array_like
#         Hermitian (symmetric if all elements are real), positive-definite
#         input matrix.
#     upper : bool
#         If ``True``, the result must be the upper-triangular Cholesky factor.
#         If ``False``, the result must be the lower-triangular Cholesky factor.
#         Default: ``False``.

#     Returns
#     -------
#     L : (..., M, M) array_like
#         Lower or upper-triangular Cholesky factor of `a`. Returns a matrix
#         object if `a` is a matrix object.

#     Raises
#     ------
#     LinAlgError
#        If the decomposition fails, for example, if `a` is not
#        positive-definite.

#     See Also
#     --------
#     scipy.linalg.cholesky : Similar function in SciPy.
#     scipy.linalg.cholesky_banded : Cholesky decompose a banded Hermitian
#                                    positive-definite matrix.
#     scipy.linalg.cho_factor : Cholesky decomposition of a matrix, to use in
#                               `scipy.linalg.cho_solve`.

#     Notes
#     -----

#     .. versionadded:: 1.8.0

#     Broadcasting rules apply, see the `numpy.linalg` documentation for
#     details.

#     The Cholesky decomposition is often used as a fast way of solving

#     .. math:: A \\mathbf{x} = \\mathbf{b}

#     (when `A` is both Hermitian/symmetric and positive-definite).

#     First, we solve for :math:`\\mathbf{y}` in

#     .. math:: L \\mathbf{y} = \\mathbf{b},

#     and then for :math:`\\mathbf{x}` in

#     .. math:: L^{H} \\mathbf{x} = \\mathbf{y}.

#     Examples
#     --------
#     >>> A = np.array([[1,-2j],[2j,5]])
#     >>> A
#     array([[ 1.+0.j, -0.-2.j],
#            [ 0.+2.j,  5.+0.j]])
#     >>> L = np.linalg.cholesky(A)
#     >>> L
#     array([[1.+0.j, 0.+0.j],
#            [0.+2.j, 1.+0.j]])
#     >>> np.dot(L, L.T.conj()) # verify that L * L.H = A
#     array([[1.+0.j, 0.-2.j],
#            [0.+2.j, 5.+0.j]])
#     >>> A = [[1,-2j],[2j,5]] # what happens if A is only array_like?
#     >>> np.linalg.cholesky(A) # an ndarray object is returned
#     array([[1.+0.j, 0.+0.j],
#            [0.+2.j, 1.+0.j]])
#     >>> # But a matrix object is returned if A is a matrix object
#     >>> np.linalg.cholesky(np.matrix(A))
#     matrix([[ 1.+0.j,  0.+0.j],
#             [ 0.+2.j,  1.+0.j]])
#     >>> # The upper-triangular Cholesky factor can also be obtained.
#     >>> np.linalg.cholesky(A, upper=True)
#     array([[1.-0.j, 0.-2.j],
#            [0.-0.j, 1.-0.j]])

#     """

#     gufunc = _umath_linalg.cholesky_up if upper else _umath_linalg.cholesky_lo
#     a, wrap = _makearray(a)
#     _assert_stacked_2d(a)
#     _assert_stacked_square(a)
#     t, result_t = _commonType(a)
#     signature = 'D->D' if isComplexType(t) else 'd->d'
#     with errstate(call=_raise_linalgerror_nonposdef, invalid='call',
#                   over='ignore', divide='ignore', under='ignore'):
#         r = gufunc(a, signature=signature)
#     return wrap(r.astype(result_t, copy=False))


In [ ]:
# template<typename typ>
# static void
# cholesky(char uplo, char **args, npy_intp const *dimensions, npy_intp const *steps)
# {
#     using ftyp = fortran_type_t<typ>;
#     POTR_PARAMS_t<ftyp> params;
#     int error_occurred = get_fp_invalid_and_clear();
#     fortran_int n;
#     INIT_OUTER_LOOP_2

#     n = (fortran_int)dimensions[0];
#     if (init_potrf(&params, uplo, n)) {
#         linearize_data a_in = init_linearize_data(n, n, steps[1], steps[0]);
#         linearize_data r_out = init_linearize_data(n, n, steps[3], steps[2]);
#         BEGIN_OUTER_LOOP_2
#             int not_ok;
#             linearize_matrix(params.A, (ftyp*)args[0], &a_in);
#             not_ok = call_potrf(&params);
#             if (!not_ok) {
#                 if (uplo == 'L') {
#                     zero_upper_triangle(&params);
#                 }
#                 else {
#                     zero_lower_triangle(&params);
#                 }
#                 delinearize_matrix((ftyp*)args[1], params.A, &r_out);
#             } else {
#                 error_occurred = 1;
#                 nan_matrix((ftyp*)args[1], &r_out);
#             }
#         END_OUTER_LOOP
#         release_potrf(&params);
#     }

#     set_fp_invalid_or_clear(error_occurred);
# }


# template<typename typ>
# static void
# cholesky_lo(char **args, npy_intp const *dimensions, npy_intp const *steps,
#                 void *NPY_UNUSED(func))
# {
#     cholesky<typ>('L', args, dimensions, steps);
# }

# template<typename typ>
# static void
# cholesky_up(char **args, npy_intp const *dimensions, npy_intp const *steps,
#                 void *NPY_UNUSED(func))
# {
#     cholesky<typ>('U', args, dimensions, steps);
# }

In [ ]:
# template<typename typ>
# static inline void
# zero_upper_triangle(POTR_PARAMS_t<typ> *params)
# {
#     fortran_int n = params->N;
#     typ *matrix = params->A;
#     fortran_int i, j;
#     matrix += n;
#     for (i = 1; i < n; ++i) {
#         for (j = 0; j < i; ++j) {
#             matrix[j] = numeric_limits<typ>::zero;
#         }
#         matrix += n;
#     }
# }

# static inline fortran_int
# call_potrf(POTR_PARAMS_t<fortran_real> *params)
# {
#     fortran_int rv;
#     LAPACK(spotrf)(&params->UPLO,
#                           &params->N, params->A, &params->LDA,
#                           &rv);
#     return rv;
# }

# static inline fortran_int
# call_potrf(POTR_PARAMS_t<fortran_doublereal> *params)
# {
#     fortran_int rv;
#     LAPACK(dpotrf)(&params->UPLO,
#                           &params->N, params->A, &params->LDA,
#                           &rv);
#     return rv;
# }

# static inline fortran_int
# call_potrf(POTR_PARAMS_t<fortran_complex> *params)
# {
#     fortran_int rv;
#     LAPACK(cpotrf)(&params->UPLO,
#                           &params->N, params->A, &params->LDA,
#                           &rv);
#     return rv;
# }

# static inline fortran_int
# call_potrf(POTR_PARAMS_t<fortran_doublecomplex> *params)
# {
#     fortran_int rv;
#     LAPACK(zpotrf)(&params->UPLO,
#                           &params->N, params->A, &params->LDA,
#                           &rv);
#     return rv;
# }

# template<typename ftyp>
# static inline int
# init_potrf(POTR_PARAMS_t<ftyp> *params, char UPLO, fortran_int N)
# {
#     npy_uint8 *mem_buff = NULL;
#     npy_uint8 *a;
#     size_t safe_N = N;
#     fortran_int lda = fortran_int_max(N, 1);

#     mem_buff = (npy_uint8 *)malloc(safe_N * safe_N * sizeof(ftyp));
#     if (!mem_buff) {
#         goto error;
#     }

#     a = mem_buff;

#     params->A = (ftyp*)a;
#     params->N = N;
#     params->LDA = lda;
#     params->UPLO = UPLO;

#     return 1;
#  error:
#     free(mem_buff);
#     memset(params, 0, sizeof(*params));

#     return 0;
# }

# template<typename ftyp>
# static inline void
# release_potrf(POTR_PARAMS_t<ftyp> *params)
# {
#     /* memory block base in A */
#     free(params->A);
#     memset(params, 0, sizeof(*params));
# }
