## Gaussian Elimination

In this notebook, I go through the thought process (same as in class) for Gaussian Elimination, but here we turn it into Python code as opposed to pseudocode.  Then we test the code out on several different matrix systems $A\vec{x} = \vec{b}$ to see how we did!

#### Row Operations

Given some $n\times m$ matrix $A$ and an $n\times 1$ vector $\vec{b}$, we can use vanilla Gaussian Elimination to determine whether there is _one_ $\vec{x}$, _no_ $\vec{x}$, or _infinitely many_ $\vec{x}$ that satisfy $A\vec{x} = \vec{b}$.

In [46]:
import numpy as np # we are loading the package needed to make matrices

A = np.random.normal(loc = 31, scale = 2.1, size = (3,3)) # creates a 3x3 matrix from the Normal distribution with mean 31 and std 2.1
b = np.random.uniform(low = 0, high = 1, size = (3,1)) # creates a 3x1 vector from the Uniform distribution with bounds 0 and 1

Recall that a single row operation:

* focused on row $r_i$
* used a pivot in row $r_{i-1}$
* aimed to eliminate the $r_{ij}$-element using the pivot element $r_{i-1,j}$

Generally, this could look like
$$
r_i = r_i + \alpha r_{i-1},
$$

where $\alpha$ is a scalar selected purposely to eliminate the appropriate elements.  IF we use $a_{ij}$ to represent the elements of matrix $A$, then we could say that $\alpha = -a_{ij}/a_{i-1,j}$.  Notice this gives us a 0 in the element of row $r_i$ right below the pivot element $a_{i-1,j}$ when we substitute into the row operation equation:

$$
a_{ij} + (-a_{ij}/a_{i-1,j}) a_{i-1,j}.
$$

In [47]:
(n,m) = A.shape # determines number of rows and columns in A

i = 0 # we'll work with first row
j = 0 # let's just work with first element as pivot

# write the row operation more generally below so we can simply copy+paste later

p = A[i,j] # for our example, pivot is in (0,0)-position if it is non-zero

alpha = -A[i+1,j]/p # calculates the multiplier needed for row operation (always what zeroes out elements below pivot)
r = A[i+1,j] + alpha*A[i,j] # updates the element right below the pivot element

# can display alpha or r below just to see our code is working
r

np.float64(0.0)

We do want to apply the operation to an entire row at once (or to all elements in a single row, across all the columns).  So we modify the code above to take this into consideration.  Can you spot the difference?

In [48]:
i = 0
j = 0

p = A[i,j]

alpha = -A[i+1,j]/p
r = A[[i+1,]] + alpha*A[[i,]]

display(r)


array([[0.        , 0.02439724, 4.41138356]])

There is one important row operation we will need in the future, which is a row interchange.  We usually do this when pivot positions are 0 and there is a non-zero element available in the same column.  

How to do this in Python is illustrated below.  We are swapping rows (i+1) and (i+2).  Recall we let $i = 0$ earlier.

In [49]:
A[[i+2,]], A[[i+1,]] = A[[i+1,]], A[[i+2,]] # for the row swap to work in python, we need to use [[]]


#### M Elements in a Row

We will work only update one row of $A$ as a whole here.  In the next section, we'll consider all rows of $A$.

Below, we put all the pieces together for an update of row 2 in $A$.  Or, in Python, we call that row 1.

In [50]:
display(A)

for i in range(1):

    p = A[i,i]
    alpha = -A[i+1,i]/p

    A[[i+1, ]] = A[[i+1,]] + alpha*A[[i,]]

    display(A)

array([[32.67970792, 33.88671849, 27.55241148],
       [31.85208588, 29.50174918, 33.79823881],
       [30.58628579, 31.74037399, 30.19882125]])

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579, 31.74037399, 30.19882125]])

What you should find is that the second row of $A$ has been updated such that the element right below the (1,1)-element is now 0.

#### N Rows with M Elements

So, we have $n = 3$ rows in $A$.  We should stop after the second row.  What we'll do is increase the number of $i$ iterations to match $n$.

In [51]:
display(A)

for i in range(2):

    p = A[i,i]
    alpha = -A[i+1,i]/p

    A[[i+1, ]] = A[[i+1,]] + alpha*A[[i,]]

    display(A)

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579, 31.74037399, 30.19882125]])

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579, 31.74037399, 30.19882125]])

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579,  0.        , 92.68995304]])

What you should notice there is an issue!  We still haven't taken care of the a row 3 updated using the first pivot.  We need to take that into consideration with the previous code.  Whoops!   But where is the issue?  If we trace through the code, we know we want $p$ to be the same for each row, but we want $alpha$ to change.  We'll need another loop to ensure this happens.

In [52]:
display(A)

for i in range(n):

    p = A[i,i]

    for j in range(i+1,m):

        alpha = -A[j,i]/p

        A[[j, ]] = A[[j,]] + alpha*A[[i,]]

        display(A)

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579,  0.        , 92.68995304]])

array([[32.67970792, 33.88671849, 27.55241148],
       [ 0.        , -3.52677942,  6.94359926],
       [30.58628579,  0.        , 92.68995304]])

array([[ 32.67970792,  33.88671849,  27.55241148],
       [  0.        ,  -3.52677942,   6.94359926],
       [  0.        , -31.71597674,  66.90251535]])

array([[ 3.26797079e+01,  3.38867185e+01,  2.75524115e+01],
       [ 0.00000000e+00, -3.52677942e+00,  6.94359926e+00],
       [ 0.00000000e+00,  3.55271368e-15,  4.45941738e+00]])

Ah!  That's better :):):)

#### Incorporating Row Interchange

What if a pivot is zero already?  We want to find, in the same column, where the next nonzero element is.

What if there are no nonzeros in that column?  We'd move on to the next column.

So, we'll check if $p$ is 0.  If it is, do the row exchange.  Then proceed as usual.  If it's not, then proceed as usual.

You can test the code below out on the matrix from class.  I've defined it below, though that's not the $A$ we care about right now.

In [53]:
A = np.array([[1,-1,2,-1],[2,-2,3,-3],[1,1,1,0],[1,-1,4,3]])

In [54]:
for i in range(n):

    p = A[i,i]

    if p == 0:

        nxt = np.nonzero(A[i:,i]) #determine the index of all nonzeros in column i

        # need a check if the column is all 0
        if nxt[0].size == 0:
            # if yes, move on to the next column
            continue;

        else:

            g = nxt[0][0]; indx = g+i #extracts the index of nonzero element i column i AFTER row 0's element
            p = A[indx,i] #updates p

            A[[i,]], A[[indx,]] = A[[indx,]], A[[i,]] #swaps rows

    for j in range(i+1,m+1):

        alpha = -A[j,i]/p #determines multiplier

        A[j,:] = A[j,:] + alpha*A[i,:] # row operation
        display(A)


array([[ 1, -1,  2, -1],
       [ 0,  0, -1, -1],
       [ 1,  1,  1,  0],
       [ 1, -1,  4,  3]])

array([[ 1, -1,  2, -1],
       [ 0,  0, -1, -1],
       [ 0,  2, -1,  1],
       [ 1, -1,  4,  3]])

array([[ 1, -1,  2, -1],
       [ 0,  0, -1, -1],
       [ 0,  2, -1,  1],
       [ 0,  0,  2,  4]])

array([[ 1, -1,  2, -1],
       [ 0,  2, -1,  1],
       [ 0,  0, -1, -1],
       [ 0,  0,  2,  4]])

array([[ 1, -1,  2, -1],
       [ 0,  2, -1,  1],
       [ 0,  0, -1, -1],
       [ 0,  0,  2,  4]])

array([[ 1, -1,  2, -1],
       [ 0,  2, -1,  1],
       [ 0,  0, -1, -1],
       [ 0,  0,  0,  2]])

Great!  We have one last thing to do!  And that's to incorporate backward substitution so that we can actually solve a system of equations.

#### Incorporating Backward Substitution

Assume we're given a vector $\vec{b}$ with $n$ rows.  We note that solving for the $x_i$ involves backward substitution.  This involves

$$
x_i = (1/a_{ii})(b_i - \sum\limits_{j=i+1}^m a_{ij}x_{j})
$$

for each $x_i$ we solve.

We can go ahead and act as though we've concatonated $\vec{b}$ to matrix $A$ for the augmented matrix $\tilde{A}$.  Then the update looks something like

$$
x_i = (1/a_{ii})(a_{i, m+1} - \sum\limits_{j=i+1}^m a_{ij}x_j).
$$

Note this works when there is a unique solution.

We'll incorporate this into our Python code.  Note that means our method has to work for non-square matrices!  Can you observe the changes?

In [55]:
A = np.random.normal(loc = 31, scale = 2.1, size = (3,3)) # creates a 3x3 matrix from the Normal distribution with mean 31 and std 2.1
b = np.random.uniform(low = 0, high = 1, size = (3,1)) # creates a 3x1 vector from the Uniform distribution with bounds 0 and 1

In [56]:
# input: A - an nxm coefficient matrix
#        b - an nx1 vector, RHS of system of equations
# output: x - an mx1 vector that satisfies the system of equations

A_aug = np.concatenate([A,b], axis = 1)
(n,m) = A_aug.shape

# finds echelon form
for i in range(n):

    p = A_aug[i,i]
    if p == 0:

        nxt = np.nonzero(A_aug[i:,i]) #determine the index of all nonzeros in column i

        # need a check if the column is all 0
        if nxt[0].size == 0:
            # if yes, move on to the next column
            continue;

        else:

            g = nxt[0][0]; indx = g+i #extracts the index of nonzero element i column i AFTER row 0's element
            p = A_aug[indx,i] #updates p

            A_aug[[i,]], A_aug[[indx,]] = A_aug[[indx,]], A_aug[[i,]] #swaps rows

    for j in range(i+1,n):

        alpha = -A_aug[j,i]/p
        A_aug[j,:] = A_aug[j,:] + alpha*A_aug[i,:]

# backward substitution
x = np.zeros(shape = (3,1)) # create a vector of 0's to fill in
for k in range(n-1, -1, -1):

    # adding all the terms where we know the x values
    sum_of_stuff = np.sum(A_aug[k,(k+1):(m-1)] * x[(k+1):(m-1)])
    # backwards substitution
    x[k] = (1/A_aug[k,k])*(A_aug[k,(m-1)] - sum_of_stuff)
A_aug

array([[31.93237617, 28.54291299, 31.57694893,  0.87090307],
       [ 0.        , 11.43310877,  1.13394946, -0.17552672],
       [ 0.        ,  0.        , -0.07105854, -0.65292015]])

#### No Solution or Infinite Solutions

Some places where we can be more considerate:

* checking the last row at the end, after achieving echelon form.  IF there is a row of 0's and a nonzero in the last position, then we have no solution.  If there is a row of 0's, including in the last position, then we have infinite solutions.

The change is below.

In [57]:
# input: A - an nxm coefficient matrix
#        b - an nx1 vector, RHS of system of equations
# output: x - an mx1 vector that satisfies the system of equations

A_aug = np.concatenate([A,b], axis = 1)
(n,m) = A_aug.shape

# finds echelon form
for i in range(n):

    p = A_aug[i,i]

    if p == 0:

        nxt = np.nonzero(A_aug[i:,i]) #determine the index of all nonzeros in column i

        # need a check if the column is all 0
        if nxt[0].size == 0:
            # if yes, move on to the next column
            continue;

        else:

            g = nxt[0][0]; indx = g+i #extracts the index of nonzero element i column i AFTER row 0's element
            p = A_aug[indx,i] #updates p

            A_aug[[i,]], A_aug[[indx,]] = A_aug[[indx,]], A_aug[[i,]] #swaps rows

    for j in range(i+1,n):

        alpha = -A_aug[j,i]/p
        A_aug[j,:] = A_aug[j,:] + alpha*A_aug[i,:]

# find solution, if any
if np.sum(A_aug[(n-1),:] == 0) == m:

    display("There are infinite solutions.")

elif ((np.sum(A_aug[(n-1),:(m-2)] == 0)) and (A_aug[(n-1),(m-1)] != 0)):

    display("There are no solutions.")

else:

    # backward substitution
    x = np.zeros(shape = (3,1))
    for k in range(n-1, -1, -1):

        sum_of_stuff = np.sum(A_aug[k,(k+1):(m-1)] * x[(k+1):(m-1)])
        x[k] = (1/A_aug[k,k])*(A_aug[k,(m-1)] - sum_of_stuff)


'There are no solutions.'

#### Tests

Test the code above using the following systems of equations.

$$
\tilde{A} =
\begin{bmatrix}
1 & 1 & 1 & 4\\
2 & 2 & 1 & 6\\
1 & 1 & 2 & 6
\end{bmatrix}
$$
(infinite solutions)

$$
\tilde{A} =
\begin{bmatrix}
1 & 1 & 1 & 4\\
2 & 2 & 1 & 4\\
1 & 1 & 2 & 6
\end{bmatrix}
$$
(no solution)

$$
\tilde{A} =
\begin{bmatrix}
1 & 3 & 1 & 1 & 1\\
-4 & -9 & 2 & -1 & -1\\
0 & -3 & -6 & -3 & -3\\
0 & 1 & 2 & 1 & 1
\end{bmatrix}
$$
(infinite solutions)

If you come into any issues, you should figure out how to fix them!

## Your TASKs: Rebecca George, Rose Gutterman, & Taylor Kim

(1) Modify the code so that it is a function that takes in a matrix $A$ and a vector $b$.  

(2) Create a new function (copy+paste) and modify it so that it includes scaled partial pivoting.

Be sure to: document your code (include input and output descriptions); explain in text what you did to make scaled partial pivoting happen!

Whether you start a new Google Colab notebook or use this one, you should turn it in to Blackboard.

Use "run all" to make sure test cases and library imports get run too!

## Contributions:
---
### Rebecca
- put function header before provided code to make a function
- fixed some initial errors
- added scaled partial pivoting

### Rose
- reformulated infinite/zero solution check
- corrected 'continue' for moving on to the next column
- corrected scaled partial pivoting

### Taylor
- validated results
- created test cases + expected outputs
- added error checking for non-none x outputs
- fixed >1 rows post-skip error where row operation/canceling is not checked
---

## Test Cases

In [58]:
A1 = np.array([
    [1, 1, 1],
    [2, 2, 1],
    [1, 1, 2]
])
b1 = np.array([
    [4],
    [6],
    [6]
])
# x1: infinite solutions

A2 = np.array([
    [1, 1, 1],
    [2, 2, 1],
    [1, 1, 2]
])
b2 = np.array([
    [4],
    [4],
    [6]
])
# x2: no solutions

A3 = np.array([
    [1, 3, 1, 1],
    [-4, -9, 2, -1],
    [0, -3, -6, -3],
    [0, 1, 2, 1]
])
b3 = np.array([
    [1],
    [-1],
    [-3],
    [1]
])
# x3: infinite solutions

A4 = np.array([
    [1, 0, -2],
    [-2, 1, 6],
    [3, -2, -5]
])
b4 = np.array([
    [-1],
    [7],
    [-3]
])
x4 = np.array([
    [3],
    [1],
    [2]
])


A5 = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
])
b5 = np.array([
    [1.984 ],
    [ -5.049 ],
    [-3.895]
])

## Gaussian Elimination Function

In [59]:
# input: A - an nxm coefficient matrix
#        b - an nx1 vector, RHS of system of equations
# output: x - an mx1 vector that satisfies the system of equations
def GE(A,b):
  A_aug = np.concatenate([A,b], axis = 1)
  (n,m) = A_aug.shape
  A_aug = A_aug.astype(float)
  # print(f"Initial A = \n{A_aug}\n") # print initial A
  skipped = False

  # finds echelon form
  for i in range(n):
      row_ptr = i
      p = A_aug[i,i] # initially set pivot to the 'default'
      if p == 0:
          # check if the column is all 0
          # returns tuple of arrays of indexes (x_nonzeros=[], y_nonzeros=[])
          nxt = np.nonzero(A_aug[i:,i])
          if nxt[0].size == 0:
              # have some situation like the 2nd col of this:
              # [[ 1  1  1  4]
              #  [ 0  0 -1 -2]
              #  [ 0  0  1  2]]
              # there will be no unique solution
              # move on to the next column
              skipped = True
              continue
          else:
              # get index of nonzero element i column i AFTER row 0's element
              g = nxt[0][0]; indx = g+i
              p = A_aug[indx,i] # update pivot
              A_aug[[i, indx]] = A_aug[[indx, i]] # swaps rows
      else:
        if skipped:
          # if we skipped a row on the previous row,
          # check if this row cancels out above
          nxt = np.nonzero(A_aug[:i,i])
          if nxt[0].size == 0:
              continue
          else:
              indx = nxt[-1][-1]         # get lowest nonzero above i
              A_aug[[i, indx]] = A_aug[[indx, i]] # swaps rows
              row_ptr = indx                      # update row_ptr
        skipped = False

      # for all rows below current, do row operations
      for j in range(row_ptr+1,n):
          alpha = -A_aug[j,i]/p
          # print(f"Row Operation: {A_aug[j,:]} + {alpha}*{A_aug[row_ptr,:]}") # print row operation
          A_aug[j,:] = A_aug[j,:] + np.multiply(A_aug[row_ptr,:], alpha)

      # print(f"A = \n{A_aug}\n") # print A after row operation
  print(f"Final A = \n{A_aug}\n") # print end-result A

  # check for contradictions and zero-ed rows
  # this must look through more than the bottom-most row
  # ex: r4 zero-ed out, r3 A zero-ed out but not b, r2 zero-ed out
  zero_row = False
  for i in range(n):
    if (np.sum(A_aug[i,:(m-1)])==0):
      if (A_aug[i,(m-1)] != 0):
        print("There are no solutions.")
        return None
      elif (A_aug[i,(m-1)] == 0):
        zero_row = True
  # return infinite solutions outside loop to avoid assuming infinite solutions
  # when there is a row not yet iterated over which contains a contradiction
  if (zero_row and (n <= (m-1))):
      print("There are infinite solutions.")
      return None

  # backward substitution
  x = np.zeros(n)
  for k in range(n-1, -1, -1):
    sum_of_stuff = np.sum(A_aug[k,(k+1):n] * x[(k+1):n])
    x[k] = (1/A_aug[k,k])*(A_aug[k,(m-1)] - sum_of_stuff)
  return x

A = [A1, A2, A3, A4, A5]
b = [b1, b2, b3, b4, b5]

for i in range(len(A)):
  x = GE(A[i], b[i])
  if (x is not None):
    print(f"x = {x}")
    print("Difference between A*x and b for case ", i, ": ", (np.dot(A[i], x)) - b[i].reshape(1,-1))
  print("------------------\n")

Final A = 
[[1. 1. 1. 4.]
 [0. 0. 1. 2.]
 [0. 0. 0. 0.]]

There are infinite solutions.
------------------

Final A = 
[[ 1.  1.  1.  4.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -2.]]

There are no solutions.
------------------

Final A = 
[[1. 3. 1. 1. 1.]
 [0. 3. 6. 3. 3.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

There are infinite solutions.
------------------

Final A = 
[[ 1.  0. -2. -1.]
 [ 0.  1.  2.  5.]
 [ 0.  0.  5. 10.]]

x = [3. 1. 2.]
Difference between A*x and b for case  3 :  [[0. 0. 0.]]
------------------

Final A = 
[[ 1.012      -2.132       3.104       1.984     ]
 [ 0.         -0.39552569 -0.47374308 -0.86926877]
 [ 0.          0.         -8.93914077 -8.93914077]]

x = [1. 1. 1.]
Difference between A*x and b for case  4 :  [[ 0.0000000e+00 -8.8817842e-16 -8.8817842e-16]]
------------------



## Gaussian Elimination with Scaled Partial Pivoting

In [60]:
# input: A - an nxm coefficient matrix
#        b - an nx1 vector, RHS of system of equations
# output: x - an mx1 vector that satisfies the system of equations
def GE_SPP(A,b):
  A_aug = np.concatenate([A,b], axis = 1)
  (n,m) = A_aug.shape
  A_aug = A_aug.astype(float)
  # print(f"Initial A = \n{A_aug}\n") # print initial A
  S = np.amax(np.abs(A_aug), axis = 1)
  # print(f"S = {S}") # print S

  # finds echelon form
  for i in range(n):
      p=A_aug[i,i]
      # print(f"Pivot: {p}") # print pivot
      if (i<n-1):
        ratios = np.abs(A_aug[i:,i])/S[i:] # compute ratios
        # print(f"Ratios: {ratios} = {A_aug[i:,i]}/{S[i:]}") # print ratios

        p_indx = i+np.argmax(ratios) # get row of largest ratio
        p = A_aug[p_indx,i] # change pivot to largest ratio
        # print(f"Pivot changed to: {p}") # print pivot
        # if the pivot is a 0, column must be all zeros, continue to next
        if (p == 0):
            continue
        # if the pivot is on a different row from the one we are looking at, swap rows
        elif (p_indx != i):
            A_aug[[i, p_indx]] = A_aug[[p_indx, i]]

      zero = np.float64(0.0)
      if(p==zero):
        continue

      mult = A_aug[:, i] / p                # compute multipliers
      # just get all the way to reducted row echelon form
      # to take care of cases like:
      # [2 2 1   | 6]
      # [0 0 0.5 | 1]
      # [0 0 1.5 | 3]
      # handling this case without reducing would introduct extra logic infrastructure
      # I think why not just go to reduced row-echelon form
      # the textbook cuts off those cases early, but I want to now if it will be infinite or no solutions specifically
      for j in range(n):
          if (j != i):
            alpha = -mult[j]
            # print(f"Row Operation: {A_aug[j,:]} - {alpha}*{A_aug[i,:]}") # print row operation
            A_aug[j,:] = A_aug[j,:] + alpha*A_aug[i]

      # print(f"A = \n{A_aug}\n") # print A after row operation
  print(f"Final A = \n{A_aug}\n") # print end-result A

  # we have to check all rows OR fix row reordering so that we are guaranteed to move zerod-out a rows in the middle to the bottom
  # check for contradictions and zero-ed rows
  zero_row = False
  for i in range(n):
    if (np.sum(A_aug[i,:(m-1)])==0):
      if (A_aug[i,(m-1)] != 0):
        print("There are no solutions.")
        return None
      elif (A_aug[i,(m-1)] == 0):
        zero_row = True
  # return infinite solutions outside loop to avoid assuming
  # infinite solutions when there is a row not yet iterated over
  # which contains a contradiction (no solutions)
  if (zero_row):
    if (n <= (m-1)):
      print("There are infinite solutions.")
      return None

  # backward substitution
  x = np.zeros(n)
  for k in range(n-1, -1, -1):
      sum_of_stuff = np.sum(A_aug[k,(k+1):(m-1)] * x[(k+1):(m-1)])
      x[k] = (1/A_aug[k,k])*(A_aug[k,(m-1)] - sum_of_stuff)
  return x


A = [A1, A2, A3, A4, A5]
b = [b1, b2, b3, b4, b5]

for i in range(len(A)):
  x = GE_SPP(A[i], b[i])
  if (x is not None):
    print(f"x = {x}")
    print("Difference between A*x and b for case ", i, ": ", (np.dot(A[i], x)) - b[i].reshape(1,-1))
  print("------------------\n")

Final A = 
[[2.  2.  0.  4. ]
 [0.  0.  0.  0. ]
 [0.  0.  1.5 3. ]]

There are infinite solutions.
------------------

Final A = 
[[2.         2.         0.         1.33333333]
 [0.         0.         0.         0.66666667]
 [0.         0.         1.5        4.        ]]

There are no solutions.
------------------

Final A = 
[[-4.  0. 20.  8.  8.]
 [ 0. -3. -6. -3. -3.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

There are infinite solutions.
------------------

Final A = 
[[3.         0.         0.         9.        ]
 [0.         0.66666667 0.         0.66666667]
 [0.         0.         2.5        5.        ]]

x = [3. 1. 2.]
Difference between A*x and b for case  3 :  [[-4.44089210e-16  0.00000000e+00 -1.33226763e-15]]
------------------

Final A = 
[[ 3.10400000e+00  0.00000000e+00  0.00000000e+00  3.10400000e+00]
 [ 0.00000000e+00 -7.20918814e-01  8.88178420e-16 -7.20918814e-01]
 [ 0.00000000e+00  0.00000000e+00  1.59897957e+00  1.59897957e+00]]

x = [1. 1. 1.]
Difference be